volumes:
  odoo_data: {}
  conf: {}
  odoo_database: {}
  #addons_path: {}

services:
  odoo:
    container_name: odoo
    build:
      context: .
      dockerfile: ./odoo-image/Dockerfile
    image: odoo:tripart
    ports:
      - 8070:8069
      - 8888:3001
    links:
      - "db:db"
      - "wdb:wdb"
    environment:
      - ODOO_SERVER=odoo-bin
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_SOCKET_SERVER=wdb
      - WDB_WEB_PORT=1984
      - WDB_WEB_SERVER=localhost
    volumes:
      - "odoo_data:/var/lib/odoo"
      - "./addons_path:/mnt/extra-addons"
      - "./conf:/etc/odoo"
    command:
      - "--dev=all"
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: db
    volumes:
      - ./odoo_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=diazrock
      - POSTGRES_PASSWORD=1234      
      - POSTGRES_DB=odoo_data
  wdb:
    image: yajo/wdb-server:latest
    ports:
        - "1984:1984"